/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.es.view;

/**
 *
 * @author User
 */
public class AdvanceSettingPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExamSettingPanel
     */
    public AdvanceSettingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDelete = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUser1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(840, 481));

        pnlDelete.setBackground(new java.awt.Color(153, 153, 153));
        pnlDelete.setOpaque(false);
        pnlDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel24.setText("user account ");
        pnlDelete.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 144, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel25.setText("user id");
        pnlDelete.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 71, 32));

        jLabel26.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel26.setText("name");
        pnlDelete.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 80, 27));

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel21.setText("      change");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel21.setOpaque(true);
        pnlDelete.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 150, 50));

        jLabel27.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel27.setText("user privilage");
        pnlDelete.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 120, 32));

        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel28.setText("new password");
        pnlDelete.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 130, 27));

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel29.setText("password");
        pnlDelete.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 80, 27));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        pnlDelete.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 230, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        pnlDelete.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 230, 30));

        txtUser1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        pnlDelete.add(txtUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 220, -1));
        pnlDelete.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 240, 30));
        pnlDelete.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(pnlDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPanel pnlDelete;
    private javax.swing.JTextField txtUser1;
    // End of variables declaration//GEN-END:variables
}
